### ISSUE TITLE
Curren state

### ISSUE THREAD

**Issue by AntonioL** [dunglas/vulcain#75] opened 2020-12-30 23:41 UTC
Vulcain's approach is quite intriguing. However major browsers per my understanding have deprecated the h2 server push feature.

Does this mean that vulcain in current state is unusable?

I understand that it might make use of Early Hints feature in the future.

**Comment by dunglas** [comment] 2020-12-30 23:49
Hi, and thanks for your interest for Vulcain.
No Vulcain is still totally usable, even without Server Push. We support Preload links since day one and according to our recent internal benchmarks it's usually faster than using Server Push (even without Early Hints) because it allows better caching strategies.

We'll release a website explaining that soon.

Closing as duplicate of https://github.com/dunglas/vulcain/issues/70#issuecomment-726120834.

**Closed** 2020-12-30 23:49 UTC

**Comment by AntonioL** [comment] 2020-12-31 10:19
Sorry I did not spot the previous issue.

So basically in that case with "Preload" headers what would Vulcain do? It would makes those requests and deposit them in a temporary cache for being retrieved when the client asks for those resources?

So it would be acting like a caching layer?

I am just trying to picture the whole workflow in my head.
